### ISSUE TITLE
Charm upgrade from rev 108 to 166 fails

### ISSUE THREAD

**Issue by cbartz** [canonical/grafana-agent-operator#122]
### Bug Description

I am not able to upgrade an already related grafana-agent on arm substrate from rev 108 to 166 . It goes into error state with a failed upgrade-charm hook:

```
foo@bar:~$ juju status
Model                  Controller         Cloud/Region           Version  SLA          Timestamp
foobar  prodstack-is-beta  prodstack6/prodstack6  3.1.8    unsupported  10:28:58Z


App                    Version  Status  Scale  Charm          Channel  Rev  Exposed  Message
grafana-agent                   error       1  grafana-agent  edge     166  no       hook failed: "upgrade-charm"
openstack-repo-policy           active      1  github-runner           185  no       

Unit                      Workload  Agent  Machine  Public address  Ports  Message
openstack-repo-policy/9*  active    idle   190      x       
  grafana-agent/21*       error     idle            x        hook failed: "upgrade-charm"
```

### To Reproduce

1. `juju deploy whatever-compatible-machine-charm`
2. `juju deploy grafana-agent --channel=edge --revision 108`
3. `juju integrate whatever-compatible-machine-charm grafana-agent`
4. `juju refresh grafana-agent --revision 166`

### Environment

Openstack cloud, juju 3.1.8

### Relevant log output

```shell
unit-grafana-agent-21: 10:24:24 INFO unit.grafana-agent/21.juju-log Running legacy hooks/upgrade-charm.
unit-grafana-agent-21: 10:24:24 WARNING unit.grafana-agent/21.upgrade-charm Invalid type NoneType for attribute 'telemetry.sdk.version' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
unit-grafana-agent-21: 10:24:24 DEBUG unit.grafana-agent/21.juju-log ops 2.14.0 up and running.
unit-grafana-agent-21: 10:24:24 DEBUG unit.grafana-agent/21.juju-log Charm called itself via hooks/upgrade-charm.
unit-grafana-agent-21: 10:24:24 DEBUG unit.grafana-agent/21.juju-log Legacy hooks/upgrade-charm exited with status 0.
unit-grafana-agent-21: 10:24:24 ERROR unit.grafana-agent/21.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-grafana-agent-21/charm/./src/charm.py", line 565, in <module>
    main(GrafanaAgentMachineCharm)
  File "/var/lib/juju/agents/unit-grafana-agent-21/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-grafana-agent-21/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-grafana-agent-21/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-grafana-agent-21/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 301, in wrap_init
    resource = Resource.create(
  File "/var/lib/juju/agents/unit-grafana-agent-21/charm/venv/opentelemetry/sdk/resources/__init__.py", line 189, in create
    next(
StopIteration
unit-grafana-agent-21: 10:24:25 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-grafana-agent-21: 10:24:25 INFO juju.worker.uniter awaiting error resolution for "upgrade-charm" hook
```

**Comment by cbartz** [comment]
The same applies when upgrading to rev 164 (amd arch).

**Comment by sed-i** [comment]
- @cbartz we had a few updates recently to gagent on edge, would you be able try now refreshing from edge?
- @mmkay could this be related to what you're looking into now?

**Comment by mmkay** [comment]
It seems it's the same problem as described here: https://github.com/canonical/grafana-agent-operator/issues/146 . 

@PietroPasotti @ca-scribner do you remember what was the best way to upgrade for this scenario?

**Comment by lucabello** [comment]
This has likely been solved in the latest released charm. We are currently at revision `400+`, and the refresh seem to have been verified in https://github.com/canonical/tempo-coordinator-k8s-operator/issues/108 .

Closing, but please feel free to reopen if needed!
