### ISSUE TITLE
install hook fails with import errors

### ISSUE THREAD

**Issue by samuelengineer** [canonical/grafana-agent-operator#15]
### Bug Description

Sometimes grafana-agent installation fails in the install hook.  Inspecting the debug log shows import errors.

### To Reproduce

1. juju deploy grafana-agent --channel edge
2. juju deploy ubuntu
3. juju relate ubuntu grafana-agent

### Environment

Observed on lxd cloud and maas cloud.

### Relevant log output

```shell
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install Traceback (most recent call last):
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install   File "/var/lib/juju/agents/unit-grafana-agent-7/charm/lib/charms/observability_libs/v0/cert_handler.py", line 41, in <module>
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install     from charms.tls_certificates_interface.v2.tls_certificates import (  # type: ignore
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install   File "/var/lib/juju/agents/unit-grafana-agent-7/charm/lib/charms/tls_certificates_interface/v2/tls_certificates.py", line 285, in <module>
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install     from cryptography import x509
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install   File "/var/lib/juju/agents/unit-grafana-agent-7/charm/venv/cryptography/x509/__init__.py", line 7, in <module>
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install     from cryptography.x509 import certificate_transparency
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install   File "/var/lib/juju/agents/unit-grafana-agent-7/charm/venv/cryptography/x509/certificate_transparency.py", line 11, in <module>
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install     from cryptography.hazmat.bindings._rust import x509 as rust_x509
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install ImportError: libssl.so.3: cannot open shared object file: No such file or directory
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install During handling of the above exception, another exception occurred:
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install Traceback (most recent call last):
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install   File "./src/charm.py", line 20, in <module>
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install     from grafana_agent import METRICS_RULES_SRC_PATH, GrafanaAgentCharm
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install   File "/var/lib/juju/agents/unit-grafana-agent-7/charm/src/grafana_agent.py", line 31, in <module>
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install     from charms.observability_libs.v0.cert_handler import CertHandler
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install   File "/var/lib/juju/agents/unit-grafana-agent-7/charm/lib/charms/observability_libs/v0/cert_handler.py", line 51, in <module>
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install     raise ImportError(
unit-grafana-agent-7: 10:30:58 WARNING unit.grafana-agent/7.install ImportError: charms.tls_certificates_interface.v2.tls_certificates is missing; please get it through charmcraft fetch-lib
unit-grafana-agent-7: 10:30:59 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: exit status 1
unit-grafana-agent-7: 10:30:59 INFO juju.worker.uniter awaiting error resolution for "install" hook
```

**Comment by simskij** [comment]
This is the same issue as described in  https://github.com/canonical/grafana-agent-operator/issues/15. Closing this issue in favor of that one.
